bsky_handle: "hbgpalocalnews.bsky.social"
bsky_password: "i62x-fp6t-wvry-vq7h"
max_articles_per_feed: 10
rss_feeds:
  abc27local:
    name: "ABC27 Local News"
    url: "https://www.abc27.com/local-news/rss"
    tag: "abc27local"
  abc27weather:
    name: "ABC27 Weather"
    url: "https://www.abc27.com/weather/rss"
    tag: "abc27weather"
  wgal:
    name: "WGAL Top Stories"
    url: "https://www.wgal.com/topstories-rss"
    tag: "wgal"
  pennlive:
    name: "PennLive"
    url: "https://www.pennlive.com/arc/outboundfeeds/rss/"
    tag: "pennlive"
  fox43:
    name: "FOX43 News"
    url: "https://www.fox43.com/feeds/syndication/rss/news/local"
    tag: "fox43"
  theburg:
    name: "The Burg"
    url: "https://theburgnews.com/news/feed/"
    tag: "theburg"
html_sources:
  cbs21:
    name: "CBS21 News"
    url: "https://local21news.com/news/local"
    tag: "cbs21"
  spotlightpa:
    name: "Spotlight PA"
    url: "https://www.spotlightpa.org/"
    tag: "spotlightpa"
  hbgpagov:
    name: "City of Harrisburg"
    url: "https://harrisburgpa.gov/news/"
    tag: "hbgpagov"
  witf:
    name: "WITF News"
    url: "https://www.witf.org/news/regional-state-news/"
    tag: "witf"
  theburg:
    name: "The Burg News"
    url: "https://theburgnews.com/news/"
    tag: "theburg"
bad_words:
  - "Trump"
  - "Biden"
  - "NFL"
  - "Amazon"
  - "Walmart"
  - "Facebook"
  - "Google"
  - "Microsoft"
  - "Apple"
  - "Netflix"
  - "Disney"
  - "YouTube"
  - "Twitter"
  - "Meta"
  - "opinion"
  - "sweepstakes"
  - "casino"
  - "ICE"
  - "DOJ"
  - "recall"
  - "Vance"
  - "Epstein"
  - "Justice Department"
  - "WATCH:"
  - "VIDEO:"
  - "HHS"
  - "Kennedy"
  - "DHS"
  - "Eagles"
  - "Steelers"
  - "AI"
  - "artificial intelligence"
  - "chatGPT"
  - "ChatGPT"
  - "OpenAI"
  - "Episode"
  - "episode"
  - "PBS"
  - "streaming"
  - "TPUSA"
  - "Hegseth"
  - "Turning Point"
  - "CPAC"
  - "Climate"
  - "climate"
  - "Newsom"
  - "Walz"
  - "Navy"
  - "Army"
  - "Air Force"
  - "Marines"
  - "Space Force"
  - "Olympics"
  - "Olympic"
  - "FBI"
  - "CIA"
  - "NSA"
  - "Pentagon"
  - "cybersecurity"
  - "cyber security"
  - "cyber attack"
  - "Super Bowl"
  - "World Series"
  - "NBA"
  - "MLB"
  - "NHL"
  - "March Madness"
  - "WWE"
  - "WrestleMania"
  - "UFC"
  - "MMA"
  - "Iran"
  - "Russia"
  - "Ukraine"
  - "Putin"
  - "Zelensky"
  - "Kim Jong-un"
  - "North Korea"
  - "Taliban"
  - "Afghanistan"
  - "Israel"
  - "Hamas"
good_words:
  - "PSP"
  - "Dauphin"
  - "Franklin Co"
  - "Lancaster"
  - "Harrisburg"
  - "York"
  - "Adams Co"
  - "Chambersburg"
  - "Cumberland Co"
  - "Lebanon"
  - "Carlisle"
  - "Gettysburg"
  - "Pa."
  - "PA-"
  - "Pennsylvania"
  - "Susquehanna"
  - "South Central PA"
  - "Central PA"
  - "Hershey"
  - "Hershey's"
  - "Middletown"
  - "Dillsburg"
  - "Newport"
  - "Shippensburg"
  - "Waynesboro"
  - "Greencastle"
  - "Mount Holly Springs"
  - "Camp Hill"
  - "Mechanicsburg"
  - "Boiling Springs"
  - "New Bloomfield"
  - "Bellefonte"
  - "State College"
  - "Lewistown"
  - "Mifflin Co"
  - "Milton"
  - "Lewisburg"
  - "Selinsgrove"
  - "Sunbury"
  - "Bloomsburg"
  - "Berwick"
  - "Danville"
  - "Elysburg"